"$schema" = 'https://starship.rs/config-schema.json'
palette = "noctalia"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[>](purple)"
error_symbol = "[>](red)"
vimcmd_symbol = "[<](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
detect_extensions = []
detect_files = []














# >>> NOCTALIA STARSHIP PALETTE >>>
# Noctalia Starship Palette (wallpaper-based)
# Generated by Noctalia - do not edit manually

[palettes.noctalia]
# Standard colors
blue      = "#9ccbf8"
red       = "#ffb4ab"
green     = "#b7c8dc"
yellow    = "#e6b6ef"
cyan      = "#b7c8dc"
magenta   = "#9ccbf8"
white     = "#e2e2e6"
black     = "#111416"

# Extended palette (Catppuccin-compatible names)
rosewater = "#e6b6ef"
flamingo  = "#e6b6ef"
pink      = "#9ccbf8"
mauve     = "#31628a"
maroon    = "#ffb4ab"
peach     = "#e6b6ef"
teal      = "#b7c8dc"
sky       = "#b7c8dc"
sapphire  = "#b7c8dc"
lavender  = "#31628a"

# Text shades
text      = "#e2e2e6"
subtext1  = "#c1c7cf"
subtext0  = "#8b9199"

# Surface shades
overlay2  = "#8b9199"
overlay1  = "#c1c7cf"
overlay0  = "#41474e"
surface2  = "#41474e"
surface1  = "#111416"
surface0  = "#111416"
base      = "#111416"
mantle    = "#111416"
crust     = "#452250"
# <<< NOCTALIA STARSHIP PALETTE <<<
