[colors]
background = "#2b3b38FF"
text_primary = "#f2f3f3FF"
text_muted = "#afb6b5FF"
accent_primary = "#75d7c5FF"
accent_secondary = "#6ba8c7FF"
warning = "#7bb78dFF"
error = "#fd4663FF"
insert_hint = "#7bb78d80"
backdrop = "#21302dFF"

[colors.border]
focused = "#75d7c5FF"
unfocused = "#21302dFF"
scratchpad_focused = "#7bb78dFF"
scratchpad_unfocused = "#285836FF"
outer = "#1a2322FF"

[colors.overview]
background_tint = "#1a232288"
badge = "#75d7c5FF"
workspace_background = "#1a2322FF"
