[colors]
background = "#2b363bFF"
text_primary = "#f2f2f3FF"
text_muted = "#afb4b6FF"
accent_primary = "#75b6d7FF"
accent_secondary = "#6b7ac7FF"
warning = "#8b70c2FF"
error = "#fd4663FF"
insert_hint = "#8b70c280"
backdrop = "#212b30FF"

[colors.border]
focused = "#75b6d7FF"
unfocused = "#212b30FF"
scratchpad_focused = "#8b70c2FF"
scratchpad_unfocused = "#35215eFF"
outer = "#1a2023FF"

[colors.overview]
background_tint = "#1a202388"
badge = "#75b6d7FF"
workspace_background = "#1a2023FF"
