[colors]
background = "#2b363bFF"
text_primary = "#f2f2f3FF"
text_muted = "#afb4b6FF"
accent_primary = "#8baec1FF"
accent_secondary = "#7c85b6FF"
warning = "#907cb6FF"
error = "#fd4663FF"
insert_hint = "#907cb680"
backdrop = "#212b30FF"

[colors.border]
focused = "#8baec1FF"
unfocused = "#212b30FF"
scratchpad_focused = "#907cb6FF"
scratchpad_unfocused = "#392957FF"
outer = "#1a2023FF"

[colors.overview]
background_tint = "#1a202388"
badge = "#8baec1FF"
workspace_background = "#1a2023FF"
