color0 #17130c
color1 #ffb4ab
color2 #f2bf51
color3 #dfc390
color4 #b9d06d
color5 #f2bf51
color6 #dfc390
color7 #ebe1d5
color8 #9b8f7c
color9 #ffb4ab
color10 #f2bf51
color11 #dfc390
color12 #b9d06d
color13 #f2bf51
color14 #dfc390
color15 #ebe1d5

cursor                #ebe1d5
cursor_text_color     #17130c
background            #17130c
foreground            #ebe1d5
selection_foreground  #d2c5b0
selection_background  #4f4636
active_border_color   #f2bf51
inactive_border_color #4f4636
url_color             #f2bf51

active_tab_foreground   #402d00
active_tab_background   #f2bf51
inactive_tab_foreground #d2c5b0
inactive_tab_background #4f4636
cursor_trail_color      #d2c5b0
