color0 #121414
color1 #ffb4ab
color2 #aecbd9
color3 #bdc8ce
color4 #d4bfdd
color5 #aecbd9
color6 #bdc8ce
color7 #e3e2e3
color8 #8c9295
color9 #ffb4ab
color10 #aecbd9
color11 #bdc8ce
color12 #d4bfdd
color13 #aecbd9
color14 #bdc8ce
color15 #e3e2e3

cursor                #e3e2e3
cursor_text_color     #121414
background            #121414
foreground            #e3e2e3
selection_foreground  #c2c7cb
selection_background  #42484b
active_border_color   #aecbd9
inactive_border_color #42484b
url_color             #aecbd9

active_tab_foreground   #17343f
active_tab_background   #aecbd9
inactive_tab_foreground #c2c7cb
inactive_tab_background #42484b
cursor_trail_color      #c2c7cb
