color0 #212c30
color1 #fd4663
color2 #8ab1c2
color3 #7986b9
color4 #8f7cbd
color5 #abc7d3
color6 #abb3d3
color7 #f2f2f3
color8 #606c70
color9 #fd4663
color10 #8ab1c2
color11 #7986b9
color12 #8f7cbd
color13 #abc7d3
color14 #abb3d3
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1a2123
background            #1a2123
foreground            #f2f2f3
selection_foreground  #afb4b6
selection_background  #212c30
active_border_color   #8ab1c2
inactive_border_color #212c30
url_color             #8ab1c2

active_tab_foreground   #1b2022
active_tab_background   #8ab1c2
inactive_tab_foreground #afb4b6
inactive_tab_background #212c30
cursor_trail_color      #afb4b6
